### ISSUE TITLE
Angular bindings/expressions in IE

### ISSUE THREAD

**Issue by BrandonCardoso** [g00fy-/angular-datepicker#101]
The days of the week, month/year headers in the calendar aren't being calculated/replaced on IE. Even on the live demo page. https://rawgit.com/g00fy-/angular-datepicker/master/app/index.html

**Comment by eralha** [comment]
what version of IE? i'm using IE10 and it works just fine.

**Comment by k-nut** [comment]
We had the same problem. Changing the `{{bindings}}` to `ng-bind` seemed to solve the problem. Can you confirm this @BrandonCardoso ?
