### ISSUE TITLE
Background became transparent in 1.0.4

### ISSUE THREAD

**Issue by erhhung** [g00fy-/angular-datepicker#104]
It seems that something has changed from 1.0.3 to 1.0.4 that turned the solid widget background to transparent. I took these screen shots just by switching between the two versions using Bower:

This is what my 1.0.3 datepicker looked like inside a Bootstrap dialog:
![image](https://cloud.githubusercontent.com/assets/5808864/7479518/0584d910-f317-11e4-972f-b43e23f5f9a3.png)

And this is what my 1.0.4 datepicker looked like:
![image](https://cloud.githubusercontent.com/assets/5808864/7479533/2debd156-f317-11e4-9850-0861df53a197.png)

Here's the simple usage:
````
<input type="text" view="date"
    ng-blur="onDatePicked($event)"
    ng-model="edits.capture_time"
    date-time select-on-click />
````

The only styling performed:
````
[date-picker-wrapper] {
  width: 257px;
}
````

**Comment by eralha** [comment]
Will fix soon. Thanks

**Comment by mcblum** [comment]
+1

**Comment by idoo** [comment]
+1
