### ISSUE TITLE
localize the datepicker

### ISSUE THREAD

**Issue by SpencerZ** [g00fy-/angular-datepicker#105]
I try to localize it by regional like in JQuery datepicker, but it doesnt't work, and I can't find the localize or other means in index.js
is there any way to localize the datepicker?

**Comment by eralha** [comment]
https://docs.angularjs.org/guide/i18n you need to localize your angular app not only the date-picker.

**Comment by SpencerZ** [comment]
@eralha yes, you are right, I have required the angular-locale js
