### ISSUE TITLE
NaN instead of numbers in Firefox.

### ISSUE THREAD

**Issue by BaNdErOzZz** [g00fy-/angular-datepicker#109]

**Comment by eralha** [comment]
Case? plunker? js fiddle? too little information...

**Comment by BaNdErOzZz** [comment]
https://jsfiddle.net/8dg5w5we/

**Comment by BaNdErOzZz** [comment]
Sorry ! Non closed! Accidentally I pressed a button ! Link to jsfiddle - https://jsfiddle.net/8dg5w5we/
