### ISSUE TITLE
NaN instead of numbers in Firefox.

### ISSUE THREAD

**Issue by BaNdErOzZz** [g00fy-/angular-datepicker#110]
Link to JSfiddle - https://jsfiddle.net/8dg5w5we/ . Please, open in Firefox.

**Comment by eralha** [comment]
Your date string is invalid, and resulting on an invalid Date Object that are being passed to Date-picker Component http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15

**Comment by BaNdErOzZz** [comment]
Thank you. You really saved my day!

**Comment by eralha** [comment]
No problem, glad i could help!
