### ISSUE TITLE
Custom $interpolateProvider symbols are ignored

### ISSUE THREAD

**Issue by danielcrisp** [g00fy-/angular-datepicker#111]
I'm using this:

    // change delimiters
    $interpolateProvider.startSymbol('{[{').endSymbol('}]}');

But you have `{{ ... }}` hardcoded into your template, so the bindings don't work

See this issue for a solution: https://github.com/angular-ui/bootstrap/issues/235

**Comment by eralha** [comment]
Will switch for ng-bind, asap. Thanks.
