### ISSUE TITLE
How to use min-date in input?

### ISSUE THREAD

**Issue by tcervo** [g00fy-/angular-datepicker#117]
I'm using datepicker on inputs and I want to set the min-date of one input as the value of a previous input.

For example (these are formatted as jade, but you get the idea):

input#start.form-control(type="text" date-time auto-close="true" ng-model="foo.start_date" format="yyyy-MM-dd" min-view="date" view="date")

input#end.form-control(type="text" date-time auto-close="true" ng-model="foo.end_date" format="yyyy-MM-dd" min-view="date" view="date" min-date="foo.start_date")

This, however, is not working. The end date input is always starting at today's date.

**Comment by eralha** [comment]
it only add's validation to ng-model, it will set the input field with the class ng-invalid

**Comment by johannesjo** [comment]
This would be a nice feature however.
