### ISSUE TITLE
MIssing tag for 1.0.7

### ISSUE THREAD

**Issue by astik** [g00fy-/angular-datepicker#120]
Hi,
Version have been updated manually but no tag is available in Git, that means it is not available through bower.
You should consider using something like [grunt-bump](https://github.com/vojtajina/grunt-bump) or [grunt-release](https://github.com/geddski/grunt-release) for upgrading the plugin. It automatically takes care of versionning and tagging.

**Comment by eralha** [comment]
Thanks for the sugestion i will look into it.
