### ISSUE TITLE
Doesn't work with Ionic

### ISSUE THREAD

**Issue by adwolgan** [g00fy-/angular-datepicker#125]
Hi , I am trying to use your plugin with Ionic but it doesn't work with the input, the popup closes instantly.

**Comment by eralha** [comment]
I have used it with ionic, but i dind't use the input date-time directive, i found the same issue as you.
I think that is because ionic takes focus of the input field wich leads to the unexpected closing, what i did was something like this: http://plnkr.co/edit/b5BJLxTWtBrzSKcwCMsJ?p=preview

**Comment by eralha** [comment]
Let me know if this worked out for you

**Comment by adwolgan** [comment]
Yes it works very well with the button but I wish to use the input text with the auto-close option.
If this is not possible i'll try to make a dropdown button

**Comment by eralha** [comment]
Just add the attribute auto-close="true" to the datepicker directive it will work

**Comment by adwolgan** [comment]
Ok thank you, good job for the plugins :)

**Comment by eralha** [comment]
Glad i could help :+1:
