### ISSUE TITLE
Demo out of date

### ISSUE THREAD

**Issue by Ryuno-Ki** [g00fy-/angular-datepicker#129]
The live demo at https://rawgit.com/g00fy-/angular-datepicker/master/app/index.html is out of date.

First, the link to this JavaScript library is broken (you can expand the URL to a certain commit by hitting <kbd>y</kbd>, see <kbd>?</kbd> for more information).

Second, the directive API has changed. For example, `hours`-attribute seem to have no effect and `auto-close` was renamed to `dismiss`.

Please update at least that demo :)

**Comment by eralha** [comment]
There is no such attribute hours, auto-close have not been renamed, just check this a minute ago.

**Comment by Ryuno-Ki** [comment]
See `hours` here: https://github.com/g00fy-/angular-datepicker/blob/74c19e6088d546c5d3cba297211fe581459811ce/README.md#input-with-formatted-value

Found `dismiss` in https://github.com/g00fy-/angular-datepicker/blob/55826c510fbd392f4f91ceadef9ded5e0e708779/app/scripts/input.js#L52
