### ISSUE TITLE
Can you use a button with auto-close?

### ISSUE THREAD

**Issue by sweisman** [g00fy-/angular-datepicker#135]
I have this working with an input tag with auto-close. I would like to change this to a button. I am using Bootstrap 2.x, which required a bit of conversion from the sample code.

&lt;div class="btn-group"&gt;
    &lt;a class="btn dropdown-toggle" data-toggle="dropdown" href="#"&gt;{{(!data.start_date && 'Choose') || ''}}{{data.start_date | date:short}}&lt;/a&gt;
    &lt;div class="dropdown-menu" ng-click="$event.preventDefault(); $event.stopPropagation()"&gt;
        &lt;div date-picker="data.start_date"&gt;&lt;/div&gt;
    &lt;/div&gt;
&lt;/div&gt;

The input tag was:

&lt;input type="datetime" date-time auto-close="true" ng-model="data.start_date" view="hours"  /&gt;

Is there some way to do this? Removing the ng-click handler doesn't work right.

Also, is there some way to add a tooltip to alert users to click on the date itself to change? It's a nice widget, but the usage is confusing to new users.

**Comment by eralha** [comment]
hi, just add the attribute auto-close to the div it will work

**Comment by sweisman** [comment]
I did that already and it didn't work. That's why I posted here.

Also, even with the date display configured like this:

{{data.start_date | date:short}}

The time does not show up after the full select. Only the date.

**Comment by eralha** [comment]
can you create a plunker or js fiddle?

**Comment by sweisman** [comment]
My mistake. I didn't have the entire auto-close selector (auto-close="true"). Now, it does close, but when the datepicker disappears, the button remains in dropdown mode an empty element still remains.

&lt;div class="btn-group"&gt;
    &lt;a class="btn dropdown-toggle" data-toggle="dropdown" href="#"&gt;{{(!data.start_date && 'Choose') || (data.start_date | date:short)}}&lt;/a&gt;
    &lt;div class="dropdown-menu" ng-click="$event.preventDefault(); $event.stopPropagation()"&gt;
        &lt;div date-picker="data.start_date" view="hours" auto-close="true"&gt;&lt;/div&gt;
    &lt;/div&gt;
&lt;/div&gt;

**Comment by sweisman** [comment]
Never mind this.

I would like to disable the input when open so users can't manually change the value. That's my goal in any case.

So another question that is related. Going back to the original &lt;input&gt; element, is there a way to know when the calendar is open or closed so I can disable it with an ng-disable?
