### ISSUE TITLE
Update npm module to the last version

### ISSUE THREAD

**Issue by marduke182** [g00fy-/angular-datepicker#142]
Hi,

I want to use this library, but the current version (1.0.5) in npm, has some errors, and my solution only works with npm. It is possible publish the current version (1.0.12) in npm?

Thank you, in advance.

**Comment by trickeyone** [comment]
Just want to up-vote this as the npm version is not being updated/maintained.

**Comment by hectopod** [comment]
+1

**Comment by krzychukula** [comment]
+1

**Comment by simonsayscode** [comment]
Can you push out the latest 2.0.3 to npm since the current version there is 1.0.5 whereas the version on bower is up to date?

**Comment by retroj** [comment]
+1

**Comment by reinvanleirsberghe** [comment]
+1

**Comment by alex88** [comment]
+1 can you push this?

**Comment by AdamSelene** [comment]
Definitely needed since we're not using bower (can't). Thanks!

**Comment by rayronvictor** [comment]
+1

**Comment by scottwio** [comment]
+1

**Comment by rayronvictor** [comment]
For those who need the version 2.1.1, I recommend using the commit version from github while this version is not published.

`npm install --save g00fy-/angular-datepicker#367be7e`

**Comment by rayronvictor** [comment]
To install the latest version:

`npm install --save github:g00fy-/angular-datepicker`
