### ISSUE TITLE
build suddenly breaking on "angular-moment" not found

### ISSUE THREAD

**Issue by guy-mograbi-at-gigaspaces** [g00fy-/angular-datepicker#149]
seems that 10 days ago, a dependency was added as a patch version. 
this breaks backwards compatibility.

**Comment by eralha** [comment]
You sugest remove that dependency?

**Comment by astik** [comment]
If backward compatibility is broken, the version number should reflect that change.
As latest version upgrade were patches (x.x.y to x.x.y+1), compatibility should be preserved.
2 actions to do :
- in the current 1.0.x branch : remove the angular-moment dependency
- if angular-moment is the future of angular-datepicker, create a 1.1.0 version.

**Comment by astik** [comment]
Change was introduced in 1.0.13. Project is now in 1.0.16 ... seems kinda difficult to rollback all changes =/

**Comment by eralha** [comment]
Moment removed from dependencies.
