### ISSUE TITLE
Dist files names

### ISSUE THREAD

**Issue by Kash0** [g00fy-/angular-datepicker#155]
After installing from bower, in folder dist, I have files named like index.js, index.css etc. It is bad and can't be normally used in project without rename by hand, I think dist files must be like angular-datepicker.js instead of index. Thank you

**Comment by kejwmen** [comment]
In component's bower.json, that part:
````
"main": [
    "./dist/index.js",
    "./dist/index.css"
  ]
````
should be changed to:
````
"main": [
    "./dist/angular-datepicker.js",
    "./dist/angular-datepicker.css"
  ]
````

Beside of that, changes in dist filenames between patch versions should not happen.
