### ISSUE TITLE
Output data format

### ISSUE THREAD

**Issue by xskid** [g00fy-/angular-datepicker#163]
<input type="datetime" date-time class="form-control" min-view="date" view="date" format="dd-MM-yyyy HH:mm" ng-model="arr.startDate">

What appears @ html: 15/11/2015 which is nice.

What appears @ controller: Thu Oct 15 2015 01:00:00 GMT+0100 which is not nice.

How can I have the same output format ?

**Comment by vince2925** [comment]
I had a similar situation, and what I did was creating an mini function, like this one:
  function makeNormal($scope) {
            return $filter('date')($scope, "dd-MM-yyyy");
        };
 directly in controller and I was using it to filter my ng-models...

**Comment by xskid** [comment]
Didnt work, vince. I mean, it did the trick but didnt transform my date dd-MM-yyyy, but MM-dd-yyyy. Dunno.
