### ISSUE TITLE
Timezone Issue

### ISSUE THREAD

**Issue by santiagovazquez** [g00fy-/angular-datepicker#164]
Hi all,

I'm from Argentina which has a GMT-03 timezone:
<img width="199" alt="screen shot 2015-10-05 at 11 40 05 am" src="https://cloud.githubusercontent.com/assets/520412/10283434/fb0c4cfe-6b55-11e5-9c60-7a5c4635cfc8.png">

As you can see the component displays three hours from the previous day and if I select one of those, the component changes my previous day selection.

Maybe this is the desired behaviour but it feels very weird. 
The problem is within getVisibleHours which is using createNewDate function. It uses Date.UTC internally to create dates.

<img width="672" alt="screen shot 2015-10-05 at 11 45 26 am" src="https://cloud.githubusercontent.com/assets/520412/10283588/9a42e6ca-6b56-11e5-97be-445b2ed7297a.png">

Why the component is using UTC and not the browser TZ?

Thanks,

**Comment by santiagovazquez** [comment]
I see that the change was made by @astik .

Can you help me with this?

**Comment by astik** [comment]
Indeed it was made by me.
UTC was used in order to make unit test work ... it was not a good idea.
I am planning on working it a different way, in order to display hour to select without depending on TZ.

**Comment by santiagovazquez** [comment]
Thanks for the quick response @astik. I will work on a fix for this and I'll let you know if I reach a quick solution.
