### ISSUE TITLE
Has anyone got the min-date max-date working?

### ISSUE THREAD

**Issue by StuartBAutotrader** [g00fy-/angular-datepicker#189]
I have tried just about everything to get it working but no joy.

Here is my code...

                  <div class="input-append input-prepend" date-time-append>
                        <input id="nct" type="text" ng-model="stockItem.nctExpiry"
                               date-time
                               view="month"
                               max-view="year"
                               min-view="month"
                               format="yyyy/MMMM"
                               auto-close="true"
                               min-date="2015-10-27"
                               max-date="2015-12-27"
                               watch-direct-changes />
                        <span class="add-on"><i class="icon-calendar"></i></span>
                    </div>

Any help would be great.

Cheers

Stuart

**Comment by StuartBAutotrader** [comment]
Great update with V 2.0.0 I have found the min - max easy to implement with the new code.

Thank you.

**Comment by lukaszgrolik** [comment]
@StuartBAutotrader can you tell how you implemented min/max date? I feel like I've tested every possible combination:
```
min-date="datePickerOptions.minDate"
min-date="{{datePickerOptions.minDate}}"
```
```js
$scope.datePickerOptions = {
  minDate: '2015-09-15',
  // or
  minDate: moment('2015-09-15'), // also .format(), .toString(), .toDate()
};
```
but nothing works, I'm able to select any date and input still contains `ng-valid ng-valid-min ng-valid-max` classes. I'm using angular-datepicker 2.0.3, moment 2.10.6, angular 1.4.3

**Comment by lukaszgrolik** [comment]
It seems to work with the latest commits from master. When the next version will be released?

**Comment by alistercatch** [comment]
+1

**Comment by lapinvert** [comment]
+1 
this will work
`bower install https://github.com/g00fy-/angular-datepicker.git#28c312d6d1 --save`
