### ISSUE TITLE
Callback work with date-range?

### ISSUE THREAD

**Issue by uiktiomasfeliz** [g00fy-/angular-datepicker#195]
Here is my code

`<div class="dropdown-menu" ng-click="$event.preventDefault();$event.stopPropagation()">
                      <div date-range start="since" end="until" date-change="feedME"></div>
                  </div>`
i try this too:
`<div class="dropdown-menu" ng-click="$event.preventDefault();$event.stopPropagation()">
                      <div date-range start="since" end="until" date-change="feedME()"></div>
                  </div>`

i can pick date, everithing work's. I cant fire callback.

**Comment by DanTalash** [comment]
* Your syntax appears correct (the first one: `date-change="feedME"`)
* Is `feedME` a function which exists in the scope, or a parent scope?
* See the [demo page](https://rawgit.com/g00fy-/angular-datepicker/master/app/index.html) for an example of the callback usage. 
  * Note that selecting a date in the range element fires the callback function, which changes the callback text in the scope and prints the new date to the console.
* If it is still not working, please create a [plunker](http://plnkr.co/) or similar to illustrate the problem, or provide more of your code / HTML

**Comment by uiktiomasfeliz** [comment]
Yes is a $scope function. But i used watcher's.

**Comment by chrisdevc** [comment]
Hi, I have the same exact issue. Did you manage to solve this? thanks
