### ISSUE TITLE
Start with an empty input field

### ISSUE THREAD

**Issue by StuartBAutotrader** [g00fy-/angular-datepicker#199]
Hi, Is there any way to start with an empty input field (not date pre-set), my field is not required and I would like a blank/empty input field to start with.

**Comment by DanTalash** [comment]
Unfortunately I cannot think of any way that don't require modifying the library.

If you're fine with making modifications to the library, then you can achieve this effect by doing the following:

* Edit [this line](https://github.com/g00fy-/angular-datepicker/blob/master/dist/angular-datepicker.js#L30) of the date-picker and replace the return statement to return the text you want to see. Eg, `return '';` would result in an empty string.
* Pass an invalid date into the picker (such as `false`). The date will be displayed as whatever text you edited the above line to return.

**Comment by johannesjo** [comment]
Had the same problem. You could also use a decorator:
```javascript
angular.module('yourModule')
    .config(function ($provide)
    {
        $provide.decorator('mFormatFilter', function ()
        {
            return function newFilter(m, format, tz)
            {
                if (!(moment.isMoment(m))) {
                    return '';
                }
                return tz ? moment.tz(m, tz).format(format) : m.format(format);
            };
        });
    });

```

**Comment by StuartBAutotrader** [comment]
Thanks guys I will give this a try.

**Comment by StuartBAutotrader** [comment]
Great fix, decorator is a fantastic why of working. Thanks for your help.

**Comment by johannesjo** [comment]
@DanTalash Thanks for sharing the correct line of code :)

**Comment by mahmutduva** [comment]
Hi this solutions when i want empty input but when i receive string date from service, input will be empty. For example when service give me '2016-02-03' string date, input field will be empty.
@johannesjo 
@DanTalash

**Comment by luisantruiz** [comment]
Hi guys, I was looking for how to implement this decorator, do you have a plunker example? It's because in my case it's not working as expected. Thanks in advance.

**Comment by Dr1Ku** [comment]
Would be fixed by PR https://github.com/g00fy-/angular-datepicker/pull/293

**Comment by KlassJ** [comment]
> Had the same problem. You could also use a decorator:

It's a great one but

instead of 
`return tz ? moment.tz(m, tz).format(format) : m.format(format);`

Use  (the first one return blank if tz is undefined)
`return tz ? moment.tz(m, tz).format(format) : moment(m).format(format);`

**Comment by chinmay235** [comment]
@johannesjo  after I add your code I am getting this errror message -

**Error: [$injector:modulerr] Failed to instantiate module myModule due to:
[$injector:unpr] Unknown provider: mFormatFilterProvider**

**Comment by johannesjo** [comment]
@chinmay they probably changed it in some way or the other. I'm afraid that you will have to check their code where and if to apply the decorator.

**Comment by chinmay235** [comment]
thanks @johannesjo 
Now This is working fine. Here is my code : https://angularjscript.github.io/angularjs-datepicker/chinu.html

I have faced another issue. can you please see  above link. When I will select any date each time I am getting previous date from the input date. I select `2017-02-15`  I am getting `"due_date": "2017-02-14T19:00:00.000Z"` in my controller. Can you please fix it

**Comment by johannesjo** [comment]
@chinmay: you probably want to open a new issue.

**Comment by chinmay235** [comment]
@johannesjo I have opened a new issue. Please go https://github.com/g00fy-/angular-datepicker/issues/320
