### ISSUE TITLE
Calendar panel positioning

### ISSUE THREAD

**Issue by bragma** [g00fy-/angular-datepicker#207]
Hi,
I have a problem with the position of the calendar panel when it's opened by clicking on the input field. Basically it opens exactly over the field, hiding the contents. Sometimes I even see the cursor of the field over the calendar. I've seen the problem with both Edge and Chrome on the live demo.
Is it a CSS issue?

**Comment by DanTalash** [comment]
This was a CSS issue, which has now been resolved. Re-check the demo.

**Comment by bragma** [comment]
It works now thanks!
