### ISSUE TITLE
$error.required doesn't work

### ISSUE THREAD

**Issue by fabiopittoli** [g00fy-/angular-datepicker#210]
I've tried to validate my input date (required) but the error message never show up using angular-datepicker. What's wrong?

                            <div class="col-sm-10">
                                <div class="input-group date">                                    
                                    <input type="text" name="vigenciaInicio" placeholder="Data de início de vigência da autorregularização" class="form-control" data-mask="99/99/9999" min-view="date" max-view="date" date-time format="DD/MM/YYYY" ng-model="ctrl.autorregularizacao.VigenciaInicio" auto-close="true" required>                                                                        
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>                                    
                                </div>
                                <div class="m-t-xs" ng-show="ctrl.formGeral.$dirty">
                                    <small class="text-danger" ng-show="ctrl.formGeral.vigenciaInicio.$error.required">A data de início da vigência deve ser informada</small>                                    
                                </div>                                                                
                            </div>

**Comment by jegor-clausematch** [comment]
Try to use `ctrl.formGeral.vigenciaInicio.$error.parse` instead of `ctrl.formGeral.vigenciaInicio.$error.required`

**Comment by fabiopittoli** [comment]
Yes! It works! Thank you, jegor-clausematch!
