### ISSUE TITLE
can u tell us how can we set weekstart on calendar?

### ISSUE THREAD

**Issue by kamleshprajapati** [g00fy-/angular-datepicker#214]
can u tell us how can we set weekstart on calendar? we are very frustrate about these issue so let us know if have any solution asap.

**Comment by DanTalash** [comment]
Hi, this is not currently an option in the library.

However, I have implemented the option today and updated my most recent PR (#212) to include it.

To see the option in action before the PR is merged, check out [my demo](https://rawgit.com/DanTalash/angular-datepicker/master/app/index.html) (see bottom of left column)
