### ISSUE TITLE
Too much space between input and datepicker when two inputs with datepickers are next to each other

### ISSUE THREAD

**Issue by lehnerchristian** [g00fy-/angular-datepicker#235]
When two input fields with datepickers (date-time) are next to each other the datepicker of the right input field appears where it would appear if they were on top of each other (the left one is correct).

Am I missing something or is this a bug?

Here is a screenshot:

![screen shot 2016-02-03 at 18 47 41](https://cloud.githubusercontent.com/assets/1711080/12791763/d765725a-caa8-11e5-8000-627ec2d7c1ff.png)

**Comment by chrilehner90** [comment]
Btw. this is the markup of our input elements (jade):
```jade
input(date-time ng-model="dates.from" placeholder="{{ 'FROM' | translate }}" format="DD.MM.YYYY" min-view="date" max-date="maxDate")
|  -
input(date-time ng-model="dates.to" placeholder="{{ 'TO' | translate }}" format="DD.MM.YYYY" min-view="date" max-date="maxDate")
```

The input elements are both 100px wide.
