### ISSUE TITLE
configure week start day

### ISSUE THREAD

**Issue by sergous** [g00fy-/angular-datepicker#244]
Need for i18n set Monday as first day. Have patch for 2.0.3, attaching.

**Comment by sergous** [comment]
`Index: vendor/assets/javascripts/angular-datepicker/dist/angular-datepicker.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- vendor/assets/javascripts/angular-datepicker/dist/angular-datepicker.js	(date 1455974054000)
+++ vendor/assets/javascripts/angular-datepicker/dist/angular-datepicker.js	(revision )
@@ -4,6 +4,7 @@
 var Module = angular.module('datePicker', []);
 
 Module.constant('datePickerConfig', {
+  startingDay: 1,
   template: 'templates/datepicker.html',
   view: 'month',
   views: ['year', 'month', 'date', 'hours', 'minutes'],
@@ -355,7 +356,7 @@
 }]);
 /* global moment */
 
-angular.module('datePicker').factory('datePickerUtils', function () {
+angular.module('datePicker').factory('datePickerUtils', function (datePickerConfig) {
 var tz;
   var createNewDate = function (year, month, day, hour, minute) {
     var utc = Date.UTC(year | 0, month | 0, day | 0, hour | 0, minute | 0);
@@ -388,7 +389,7 @@
       //Grab day of the week
       var day = m.day();
 
-      if (day === 0) {
+      if (day === datePickerConfig.startingDay) {
         //If the first day of the month is a sunday, go back one week.
         m.date(-6);
       } else {
@@ -432,7 +433,7 @@
       return years;
     },
     getDaysOfWeek: function (m) {
-      m = m ? m : (tz ? moment.tz(tz).day(0) : moment().day(0));
+      m = m ? m : (tz ? moment.tz(tz).day(datePickerConfig.startingDay) : moment().day(datePickerConfig.startingDay));
 
       var year = m.year(),
         month = m.month(),
\ No newline at end of file
`

**Comment by sergous** [comment]
Here is the patch for 2.0.3
https://gist.github.com/sergous/272529713381db97942e

**Comment by Heshyo** [comment]
Actually I already sent a push request that was merged https://github.com/g00fy-/angular-datepicker/pull/231 but the code was modified again and the first day of the week is again incorrect.

**Comment by exbrain** [comment]
bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower angular-datepicker#^2.1.0       not-cached https://github.com/g00fy-/angular-datepicker.git#^2.1.0
bower angular-datepicker#^2.1.0          resolve https://github.com/g00fy-/angular-datepicker.git#^2.1.0
bower angular-datepicker#^2.1.0     ENORESTARGET No tag found that was able to satisfy ^2.1.0

Additional error details:
Available versions in https://github.com/g00fy-/angular-datepicker.git: 2.0.3, 2.0.1, 2.0.0, 1.0.20, 1.0.19, 1.0.18, 1.0.17, 1.0.16, 1.0.15, 1.0.14, 1.0.13, 1.0.12, 1.0.11, 1.0.7, 1.0.6, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 0.1.0
