### ISSUE TITLE
can I set a Date to datepick?

### ISSUE THREAD

**Issue by axetroy** [g00fy-/angular-datepicker#282]
I didn't see it in document.

some time we need set a Date to datepick

### Not This

This will change the Attr not Date

```javascript
$scope.$broadcast('pickerUpdate', 'pickerToUpdate', {
    format: 'D MMM YYYY HH:mm',
    maxDate: maxSelectableDate, //A moment object, date object, or date/time string parsable by momentjs
    minView: 'hours',
    view: false //Use default
});
```

**Comment by axetroy** [comment]
It default show Tody

But I need set it start in some day

not user **minDate** and **maxDate** to limit it

**Comment by brunokrebs** [comment]
@axetroy if you set your model with the date that you want and add the following directive:
`
 watch-direct-changes="true"
`
It will work as you expect.

**Comment by brunokrebs** [comment]
@eralha I would close this issue.

**Comment by axetroy** [comment]
@brunokrebs thanks,i will try
