### ISSUE TITLE
Blank date required

### ISSUE THREAD

**Issue by spirant** [g00fy-/angular-datepicker#41]
I am looking to see if this control can be used when a date can be entered or not depending on needs. In my case the user records the last date an event occurred, but it is possible that the event has not occurred before and should be blank. Currently the angularJS Model is not updated by clearing an input box:

    <input required="false"  format="yyyy-MM-dd" type="text" min-view="date" date-time data-ng-model="last_action">{{last_action}}

Is there a way to allow the clearing of the input box to update the model?

**Comment by vercruyssetim** [comment]
Any news on this? I am having the same issue.

**Comment by erkanarslan** [comment]
Yep, same issue here too

**Comment by Leen15** [comment]
same here!

**Comment by yohendry** [comment]
same here! HELP

**Comment by yohendry** [comment]
i solved my problem 
```javascript
Module.directive('dateRange', function () {
  return {
    templateUrl: 'templates/daterange.html',
    scope: {
      start: '=',
      end: '='
    },
    link: function (scope, element, attrs) {

      /*
       * If no date is set on scope, set current date from user system
       */
      scope.start = new Date(scope.start || new Date());
      scope.end = new Date(scope.end || new Date());

      attrs.$observe('disabled', function(isDisabled){
          scope.disableDatePickers = !!isDisabled;
        });
      scope.$watch('start.getTime()', function (value) {
        if (value && scope.end && value > scope.end.getTime()) {
          scope.end = new Date(value);
        }
      });
      scope.$watch('end.getTime()', function (value) {
        if (value && scope.start && value < scope.start.getTime()) {
          scope.start = new Date(value);
        }
      });
    }
  };
});
```

**Comment by mdedetrich** [comment]
+1

Ideally the plugin should detect if the field is optional, and if it is, then allow for blank/nullable fields

**Comment by jegor-clausematch** [comment]
I solved that problem by changing `parser` function
```javascript
function parser(viewValue) {
  if (viewValue.length === format.length) {
    return viewValue;
  }
  return (viewValue.length === 0) ? viewValue : undefined;
}
```
Now when field's value is empty it doesn't throw `parse` error and if `ng-required` is set then it will throw `required` error.
Additionally if you want to show empty field by default, then you can change Moment format filter:
```javascript
Module.filter('mFormat', function () {
  return function (m, format, tz) {
    if (!(moment.isMoment(m))) {
      return (m) ? moment(m).format(format) : '';
    }
    return tz ? moment.tz(m, tz).format(format) : m.format(format);
  };
});
```

**Comment by pavankumarkatakam** [comment]
Hi @jegor-clausematch , i think you want to try a pull request with specified gotchas.

**Comment by Maximaximum** [comment]
I guess the issue has been fixed by @jegor-clausematch, so this github issue should be closed.

However, it tricked me that this very important fix is already in the repository, but there haven't been a release since the pull request merge.

**Comment by spirant** [comment]
I am no longer using this datepicker so I will trust @Maximaximum that the fix is now there.

**Comment by LunaCh** [comment]
I use this way to clear chosen date in my controller
`angular.element("#mydate").val("");`

And my html code is:
`<input type="datetime" id="mydate" class="form-control datetimebox" date-time 
            	ng-model="dateTimeValue" date-change="onChange" auto-close="true"
            	watch-direct-changes="true">`

Hope this will help
