### ISSUE TITLE
Autoclose

### ISSUE THREAD

**Issue by Opa-** [g00fy-/angular-datepicker#72]
Autoclose of the datepicker when selecting a value on the min-view would be very appreciated :+1:

**Comment by dnlmzw** [comment]
+1 to that.

**Comment by dnlmzw** [comment]
Alternatively to:
```javascript
$('.dropdown-toggle').parent().removeClass('open');
```
If you don't want to point to a specific element, you can replace it with:
```javascript
setTimeout(function(){ scope.$emit('$destroy'); }, 1);
```

**Comment by eralha** [comment]
I think this should be optional, like a flag on the date-picker directive like "<... auto-close='true' />"

**Comment by pkalkman** [comment]
I agree with @eralha. In mine opinion that's a big +1

Any plans for implementing that

**Comment by eralha** [comment]
I can implement that, i just need to give it a little more thinking, because you can manage the visibility of the datepicker with so many things for exp: ng-class, ng-visible etc... i need to see if the implementation doesn´t clash with any functionality

**Comment by Targun** [comment]
Yes, please add :+1:

**Comment by eralha** [comment]
Closed, you can set the attribute auto-close="true" to use this feature.

**Comment by FanJUVE** [comment]
I am sorry, but auto-closing is execute without BLUR of input field (if date-time is on the input-field). And then i need to unfocus input-field manualy
