### ISSUE TITLE
Is it still active ?

### ISSUE THREAD

**Issue by loicknuchel** [g00fy-/angular-datepicker#74]
Hi,

Is this repo still active ?
Your datepicker seems really interesting but 
 - bower install is completly broken (no main files declared in bower version, wrong version numbers 1.0.0 instead of 1.0.3...)
 - many pull resquests not merged and issue not responded
 - demo is a little broken
 - documentation is really poor ...

I would love to help on some parts but I want to be sure that this repos is still active and my work will be usefull.

Thanks !

**Comment by bramski** [comment]
Open source project @johannesjo.  Seems that @g00fy- is not too interested in keeping this up to date.  You are always allowed to fork and move on.

**Comment by bramski** [comment]
@JoshWillik this datepicker totally requires bootstrap.  I think you missed the reference in app/styles deepdown where this library statically includes bootstrap 2.3.2 which is causing me major conflicts on the rest of my UI.  I can't call this library very "pure".

**Comment by owkwen** [comment]
@bramski I use this datepicker without bootstrap. There is an index.min.css in /dist/, it works perfectly.

**Comment by wannymiarelli** [comment]
@owkwen I use it too, with semantic-ui but the layout, using the index.min.css is broken.

**Comment by johannesjo** [comment]
@bramski no offense, but forking usually results in many half-assed non-coordinated efforts by different people. At the moment there are at least 3 notable angular-datepickers projects out there on github and none of them works and all of them have a lot of unattended pull-requests (not to speak of the open issues). I don't see how making another fork will make this situation any better.

**Comment by bramski** [comment]
I prefer whole assed @johannesjo.  But this project didn't work out for my needs at all so I never forked and did anything with it.  Have fun.

**Comment by g00fy-** [comment]
I am looking for people that would help maintain this project, so if any of you are interested please leave comment at #78
