### ISSUE TITLE
How to remove timer from the picker

### ISSUE THREAD

**Issue by uikro** [g00fy-/angular-datepicker#83]
Is there a way to remove the time and use only datepicker?

**Comment by eralha** [comment]
I didn't get what you are trying to accomplish, can you elaborate a bit more? is this a issue?

**Comment by Jasnan** [comment]
@eralha I think what he is trying to accomplish is to use the picker to only pick Date without time attached.

**Comment by uikro** [comment]
That's exactly what I'm trying to do. I want only a datepicker not a datetimepicker.
Sent from my BlackBerry wireless device from MTN

-----Original Message-----

**Comment by Jasnan** [comment]
@uikro It is possible with `min-view` attribute...set it to 'date'.. here is an example

<input type="datetime" date-time name="ce_dob" ng-model="newEmp.ce_dob" min-view="date" class="form-control" format="short" required>

Then you won't see the view for selecting time..hopes that helps..

**Comment by uikro** [comment]
I did that. It worked but with another problem. It doesn't close after date is picked and also,  if the date picker is located at the bottom of a long form there is a jump to the top of the page when a date is picked.
Sent from my BlackBerry wireless device from MTN

-----Original Message-----

**Comment by uikro** [comment]
Hello. How do i trigger an event when a new date is picked?

**Comment by eralha** [comment]
Hi you can't trigger an event when a new date is set, you can insted use watch function to check for changes in the ng-model value used in the date picker.

**Comment by uikro** [comment]
I tried it but it didn't work.

Datepicker:
<div class="form-group" id="data_2">
                                                <div class="input-group date">
                                                    <input type="datetime" class="input-sm form-control" date-time data-ng-model="myDate" view="date" min-view="date">
                                                    <span class="input-group-btn">
                                                        <button data-ng-click="loadClassAttendance()" class="btn btn-sm btn-white" type="button"><i class="fa fa-calendar"></i> View</button>

                                                    </span>
                                                </div>
                                            </div>
                                            <span>
                                                {{myDate}}
                                            </span>
Angular:
$scope.myDate = new Date();

   $scope.$watch('myDate', function () {
       alert("yes!")
    });

**Comment by eralha** [comment]
```javascript
<input type="datetime" class="input-sm form-control" date-time ng-model="myDate" view="date" min-view="date">
```

You have data-ng-model it's ng-model

**Comment by uikro** [comment]
Both gave the same result.

**Comment by eralha** [comment]
Check this plunkr http://plnkr.co/edit/94TifOjXZjEAhA25Kl4A?p=preview

**Comment by uikro** [comment]
```html

Error: [ngModel:nonassign] Expression 'mydate | date : 'dd-MM-yyyy'' is non-assignable. Element: <input type="text" name="bDay" ng-model="mydate | date : 'dd-MM-yyyy'" id="" value="" ng-click="showDatePicker('bday')">

```

**Comment by uikro** [comment]
Hello @eralha it worked. But the css is not working.

**Comment by eralha** [comment]
I can't help without any more details...

**Comment by uikro** [comment]
![p1](https://cloud.githubusercontent.com/assets/6927818/6686994/e7a60d4c-cca6-11e4-930a-71fd9b6a3df5.png)

**Comment by eralha** [comment]
I could be many things its hard to get what it is, i will close this issue since this now seems to me an issue in or code and not the date picker.

**Comment by chinmay235** [comment]
@uikro thank your for your well try.

You just use `format="YYYY-MM-DD"`

here is example - 

`<input type="datetime" date-time name="ce_dob" ng-model="newEmp.ce_dob" format="YYYY-MM-DD" min-view="date" class="form-control" format="short" required>`
