### ISSUE TITLE
week selection?

### ISSUE THREAD

**Issue by postixo** [g00fy-/angular-datepicker#84]
hi,

you think it's possible to add week selection?

i'm trying to show selected week after select a day instead the actual day. 

my goal is to use this datepicker as an indicative calendar based on interactions and then show the user in a mini calendar the current week.

![capture](https://cloud.githubusercontent.com/assets/7966071/6557800/bc699b04-c66f-11e4-842f-2780a862aae8.PNG)

thanks

**Comment by eralha** [comment]
Hi there, i don't see this as an issue, it's a specific request for your case, i don't see this feature get implemented in the near future.

Thanks.
