### ISSUE TITLE
Datepicker directive: "ng-model" value must be a Date object ...

### ISSUE THREAD

**Issue by luke82** [g00fy-/angular-datepicker#89]
Sometimes I get the error (on input focus, TAB):

Datepicker directive: "ng-model" value must be a Date object, a number of milliseconds since 01.01.1970 or a string representing an RFC2822 or ISO 8601 date.

Have you ever met with this error?
Thank you

**Comment by eralha** [comment]
Can you send a plunker with example?

**Comment by victortey** [comment]
```javascript
<input type="datetime" class="form-control" min-view="date" auto-close="true" date-time ng-model="timesheetDate" view="date">
```
Hi, in my html I have set the ng-model to ng-model="timesheetDate" and in my controller i have specify

$scope.timesheetDate;

however whenever I change the value of the date, it does not bind to $scope.timesheetDate

Am i missing something?

**Comment by eralha** [comment]
@victortey check this issue please for your case https://github.com/g00fy-/angular-datepicker/issues/90
