### ISSUE TITLE
date-time directive model value not updating

### ISSUE THREAD

**Issue by NtimYeboah** [g00fy-/angular-datepicker#90]
I have date-time directive on input element, but the model is not updating.
This is the plnkr http://plnkr.co/edit/4CDmSLZ6VO939jpnIZGB?p=preview

**Comment by eralha** [comment]
date-time directive have its own scope, you have tu use the form value the is exposed to the scope.

http://plnkr.co/edit/OsP3uGYGK5hYEPuwgynS?p=preview

**Comment by evdoks** [comment]
I know the issue is closed, and the other way to get over the 'own scope' issue is to user `ng-model=$scope.date', but is there is any particular reason for such behaviour? Why does it have to be a new scope? Seems to be making things more complicated.

**Comment by Mr-Anonymous** [comment]
I agree with @evdoks. Does the datepicker need to have its own scope? I am using this in a custom directive with isolated scope that calls the date-time and the model is not updating.
