### ISSUE TITLE
Set calendar to start month

### ISSUE THREAD

**Issue by sn0lan** [g00fy-/angular-datepicker#91]
On load, when I pass the start and end in, is there a way to set the calendar view to show the month that is selected, not the current month?

**Comment by eralha** [comment]
It's a bug, i will fix it.

**Comment by eralha** [comment]
Fixed: http://plnkr.co/edit/94TifOjXZjEAhA25Kl4A?p=preview

**Comment by sn0lan** [comment]
Is there a way to get this working with the date-range directive as well? This doesn't seem to work with it and that's what Im using on the project.

**Comment by eralha** [comment]
Done, http://plnkr.co/edit/RCRq761aCiImDpbv7OmB?p=preview
