### ISSUE TITLE
bower.json main property missing

### ISSUE THREAD

**Issue by AndyOGo** [g00fy-/angular-datepicker#95]
Hey guys,

Your bower.json misses the main property as defined here:
http://bower.io/docs/creating-packages/

This information is needed for tools like wiredep
https://github.com/taptapship/wiredep

Adding this to your bower.json is enough:
```json
"main": [
"./dist/index.css",
"./dist/index.js"
],
```
cheers

**Comment by eralha** [comment]
https://github.com/g00fy-/angular-datepicker/blob/master/bower.json it have the section you mention.

**Comment by AndyOGo** [comment]
true, I think I was wrong here
