### ISSUE TITLE
.dropdown-menu class missing in dist/index.css

### ISSUE THREAD

**Issue by AndyOGo** [g00fy-/angular-datepicker#96]
position:relative date pickers are broken because .dropdown-menu is missing in dist/index.css

**Comment by eralha** [comment]
Fixed!

**Comment by mpickell** [comment]
was `.dropdown-menu` included in the library earlier?  Bootstrap also has a `.dropdown-menu` and I was inheriting styles from that, so this broke all of that styling.. I probably shouldn't have been doing that but now i'm just trying to make sure i understand the fix so i update my code the right way.

**Comment by eralha** [comment]
.dropdown-menu was included earlier, it has been removed from date-picker with this fix.

**Comment by mpickell** [comment]
i'm sorry... i meant was it included in the CSS files?  did it have styling?

**Comment by eralha** [comment]
Previous from this commit the date-time directive has class="dropdown-menu", it has been removed.
