### ISSUE TITLE
Input field - actually a button

### ISSUE THREAD

**Issue by TeodorKolev** [g00fy-/angular-datepicker#98]
Input fields did not respond on changing selected date in. It works actually like button.
Is there a option to edit selected date in input, because this is proper behaviour?

**Comment by eralha** [comment]
Can you elaborate with a plunker?

**Comment by TeodorKolev** [comment]
My point is that you can't change value from input by hand, and that to works because it did not respond. So there is no difference between button and input. Input is not an input its actually a button.

**Comment by eralha** [comment]
that is not an intended behavior.

**Comment by TeodorKolev** [comment]
Indeed, it should be updated, if not - its pure button
